# import Reputation from 'common.gql'
# import ArticleHeader from 'article.gql'
# import CommentWithLocation from 'comment.gql'

# 個人頁

type User {
    id: String!
    reputations: [Reputation!]!
    about: String! # 一段自我介紹
    articles: [ArticleHeader!]!
    comments: [CommentWithLocation!]!
}

type MoreUserInfo {
    articles: [ArticleHeader!]!
    comments: [CommentWithLocation!]!
}

type Query {
    user(id: String!): User

    # 下拉時取得更舊的資訊，在 date 之前的前 number 筆資訊
    moreUserInfo(id: String!, date: String!, number: Int): MoreUserInfo
}